# Generated by Django 4.0.4 on 2022-04-29 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_binary', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.TimeField(auto_now_add=True)),
                ('poem_en', models.TextField()),
                ('poem_cn', models.TextField()),
                ('art_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WNFA_text_to_art.art')),
            ],
        ),
    ]
