# Generated by Django 4.0.4 on 2022-04-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WNFA_text_to_art', '0002_alter_record_art_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='request_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
