# Generated by Django 4.0.4 on 2022-04-29 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WNFA_text_to_art', '0003_alter_record_request_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-request_time']},
        ),
    ]
