# Generated by Django 4.0.4 on 2022-05-01 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WNFA_text_to_art', '0004_alter_record_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art',
            old_name='image_binary',
            new_name='data',
        ),
    ]
