# Generated by Django 4.0.4 on 2022-05-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WNFA_text_to_art', '0005_rename_image_binary_art_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='emotion_data',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
    ]
